name: Tests
on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -U pytest
          pip install -U -r requirements.txt
      - name: Run tests
        run: |
          cd decryptor/tests
          pytest